[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      frame-src 'self' https: http: data: blob:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https: http: data: blob:;
      connect-src 'self' https: http: wss: ws: data: blob: https://api.themoviedb.org https://*.supabase.co https://*.auth0.com https://vidfast.pro https://vidsrc.icu https://vidlink.pro https://vidsrc.cc https://player.videasy.net https://*.vidfast.pro https://*.vidsrc.icu https://*.vidlink.pro https://*.vidsrc.cc https://*.videasy.net https://streamvault-backend-bq9p.onrender.com https://vercel.live https://*.vercel.live wss://*.pusher.com https://*.jwpltx.com https://*.jwplayer.com https://*.cloudflareinsights.com https://entitlements.jwplayer.com https://prd.jwpltx.com https://lightningbolt.site https://*.lightningbolt.site;
      img-src 'self' data: https: http: blob:;
      media-src 'self' https: http: blob: data:;
      style-src 'self' 'unsafe-inline' https: http: data:;
      font-src 'self' data: https: http:;
      worker-src 'self' blob:;
      child-src 'self' https: http: data: blob:;
    """
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer-when-downgrade"
    Cross-Origin-Embedder-Policy = "unsafe-none"
    Cross-Origin-Opener-Policy = "unsafe-none"
    Permissions-Policy = "accelerometer=*, autoplay=*, clipboard-write=*, encrypted-media=*, gyroscope=*, picture-in-picture=*, fullscreen=*"

[build]
  command = "npm run build"
  publish = "dist"

